"""add filekey in task

Revision ID: ca4152854e34
Revises: bc7c3f43da62
Create Date: 2025-05-08 18:00:55.265887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4152854e34'
down_revision: Union[str, None] = 'bc7c3f43da62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('storage_type', sa.String(), nullable=True))
    op.add_column('task', sa.Column('s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 's3_key')
    op.drop_column('task', 'storage_type')
    # ### end Alembic commands ###
