"""add name in snapshot

Revision ID: d0c4a2e87ccb
Revises: be18a32b48ca
Create Date: 2025-04-29 16:41:38.936896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c4a2e87ccb'
down_revision: Union[str, None] = 'be18a32b48ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('snapshot_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'snapshot_name')
    # ### end Alembic commands ###
